### PR TITLE
Maven Surefire Plugin configuration to resolve module access issues in tests for JDK 9 and newer

### PR DESCRIPTION
**Pull request by ikardovskiy**
Maven Surefire Plugin configuration to resolve module access issues in tests for JDK 9 and newer

### CODE REVIEW

**Review by orende — APPROVED** [review]
Looks good to me! :+1:

**Review by mackapappa — DISMISSED** [review]

**Comment by orende** [comment]
@ikardovskiy After we merged another PR adding a Github Actions pipeline, we noticed that it [fails](https://github.com/citerus/dddsample-core/actions/runs/3656885308/jobs/6179839673) for this PR. Could these changes be related?

**Comment by ikardovskiy** [comment]
I'll check causes of failure today.
May be I need to add version to plugin if checks made too strict

**Comment by ikardovskiy** [comment]
I have set explicit version to surefire plugin.
But it seems to me we have some security issues in CI/CD:
```
Error: HTTP Status 403 for request POST https://api.github.com/repos/citerus/dddsample-core/dependency-graph/snapshots
Error: Response body:
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/dependency-graph#create-a-snapshot-of-dependencies-for-a-repository"
}
Error: Resource not accessible by integration
Error: HttpError: Resource not accessible by integration
```

May be it too strict for external contributors like me.

**Comment by orende** [comment]
These changes have now been incorporated into the project in commits 5aa4a76afb20546b97611884b9128680858cb8bc and 61977cf9c4c0e8cf19993972011cd0d330c2cb83 as part of another PR. Thanks!

**Pull request closed without merging**
