### PR TITLE
Refactor GraphTraversalService Implementation

### PR DESCRIPTION
**Pull request by yashTEF**
The existing findShortestPath() implementation for GraphTraversalService is cumbersome
and hard to read, hence it can be refactored and implemented in a shorter and more efficient manner.

### CODE REVIEW

**Comment by florentbo** [comment]
Why re-inventing the wheel and not using https://jgrapht.org/?

**Comment by orende** [comment]
@yashTEF The code changes look good to me, but for the sake of verifying that no regressions have been introduced, would you mind adding a unit test for the GraphTraversalService class?

**Comment by yashTEF** [comment]
@orende , there already seems to be a unit test which tests the correctness of possible routes obtained from findShortestPath in the ExternalRoutingServiceTest class under the testCalculatePossibleRoutes() method.

Is this what you are referring to?

**Comment by yashTEF** [comment]
> @orende , there already seems to be a unit test present which tests the correctness of possible routes obtained from findShortestPath in the ExternalRoutingServiceTest class under the testCalculatePossibleRoutes() method.
> 
> Is this what you are referring to?

@orende Any update, Is the above mentioned unit test sufficient or some other unit test needs to be added?

**Comment by orende** [comment]
@yashTEF Sorry about the late response. I looked at ExternalRoutingServiceTest and you're right in that it covers the functionality.

**Review by orende — APPROVED** [review]

**Pull request merged**
